"""Tercera Actualización del esquema

Revision ID: 5018be772fc5
Revises: b990180d044b
Create Date: 2025-03-29 17:29:35.183707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5018be772fc5'
down_revision: Union[str, None] = 'b990180d044b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boletos', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.drop_constraint('boletos_comprado_por_fkey', 'boletos', type_='foreignkey')
    op.create_foreign_key(None, 'boletos', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('boletos', 'comprado_por')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boletos', sa.Column('comprado_por', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'boletos', type_='foreignkey')
    op.create_foreign_key('boletos_comprado_por_fkey', 'boletos', 'usuarios', ['comprado_por'], ['id'])
    op.drop_column('boletos', 'usuario_id')
    # ### end Alembic commands ###
