"""Corrige estructura de usuarios

Revision ID: 8d2ea69f5d0d
Revises: ec5b1d83017d
Create Date: 2025-03-14 17:41:06.497302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2ea69f5d0d'
down_revision: Union[str, None] = 'ec5b1d83017d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_constraint('usuarios_correo_key', 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.drop_column('usuarios', 'correo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('correo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint('usuarios_correo_key', 'usuarios', ['correo'])
    op.drop_column('usuarios', 'hashed_password')
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###
