"""Segunda Actualización del esquema

Revision ID: b990180d044b
Revises: 4f49ce9375e6
Create Date: 2025-03-29 11:36:36.486279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b990180d044b'
down_revision: Union[str, None] = '4f49ce9375e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.Column('clasificacion', sa.String(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.Column('en_cartelera', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peliculas_id'), 'peliculas', ['id'], unique=False)
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salas_id'), 'salas', ['id'], unique=False)
    op.create_table('asientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('fila', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asientos_id'), 'asientos', ['id'], unique=False)
    op.create_table('funciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pelicula_id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['pelicula_id'], ['peliculas.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funciones_id'), 'funciones', ['id'], unique=False)
    op.create_table('boletos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcion_id', sa.Integer(), nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=False),
    sa.Column('comprado_por', sa.Integer(), nullable=False),
    sa.Column('precio', sa.DECIMAL(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['asiento_id'], ['asientos.id'], ),
    sa.ForeignKeyConstraint(['comprado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['funcion_id'], ['funciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boletos_id'), 'boletos', ['id'], unique=False)
    op.add_column('usuarios', sa.Column('creado_en', sa.TIMESTAMP(), nullable=True))
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.create_unique_constraint(None, 'usuarios', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=True)
    op.drop_column('usuarios', 'creado_en')
    op.drop_index(op.f('ix_boletos_id'), table_name='boletos')
    op.drop_table('boletos')
    op.drop_index(op.f('ix_funciones_id'), table_name='funciones')
    op.drop_table('funciones')
    op.drop_index(op.f('ix_asientos_id'), table_name='asientos')
    op.drop_table('asientos')
    op.drop_index(op.f('ix_salas_id'), table_name='salas')
    op.drop_table('salas')
    op.drop_index(op.f('ix_peliculas_id'), table_name='peliculas')
    op.drop_table('peliculas')
    # ### end Alembic commands ###
